services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: mysql://symfony:ChangeMe@database:3306/app?serverVersion=8.0&charset=utf8mb4
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
      - symfony_vendor:/app/vendor
      - symfony_node_modules:/app/node_modules
      - symfony_public_build:/app/public/build

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db-data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
  symfony_vendor:
  symfony_node_modules:
  symfony_public_build:
